[package]
name = "sell-a-maze"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-bigint = "0.4.3"
log = "0.4.14"
env_logger = "0.9.0" 
fixedbitset = "0.4.1"
xmlwriter = "0.1.0"
primes = "0.3.0"